commit
cs-ehu/Ejemplo pull request #14
Opened 2019-02-22 09:19 UTC by fedeburo

commit1

2019-02-22 14:14 UTC, FerMod submitted a review, later dismissed

2019-02-22 15:05 UTC, FerMod requested changes
El fichero debería nombrarse según lo acordado.

❌ ~`Herramienta_MarkDown.md`~

✔️ `herramienta.markdown.md`

2019-02-22 15:23 UTC, FerMod requested changes
* El fichero debería nombrarse según lo acordado. Realizar cambio de nombre:
❌ `Herramienta_MarkDown.md`
✔️ `herramienta.markdown.md`

* Archivo duplicado y en carpeta erronea. Eliminar el archivo:
[UNE157801/2 Memoria/2.05 Normas y referencias/2.5.3 Métodos, herramientas, modelos, métricas y prototipos/Herramienta_MarkDown.md](https://github.com/cs-ehu/Ejemplo/pull/14/files#diff-ae63de4e743d36fbe2f26f24e01d95cd)

2019-02-24 19:32 UTC, jiptohej approved these changes
Versión inicial

2019-02-24 19:36 UTC, merged